### ISSUE TITLE
Alacritty theme is outdated

### ISSUE THREAD

**Issue by EivindSul** [neuromaancer/everforest_collection#4]
The linked alacritty theme uses .yml, but alacritty has since moved on to .toml format. 
A new .toml theme exists at [alacritty-theme](https://github.com/alacritty/alacritty-theme), specifically [dark](https://github.com/alacritty/alacritty-theme/blob/master/themes/everforest_dark.toml) and [light](https://github.com/alacritty/alacritty-theme/blob/master/themes/everforest_light.toml).

**Comment by neuromaancer** [comment]
thanks! added it! It is better if you can have a PR.

**Comment by EivindSul** [comment]
True, I was busy with some other stuff and quickly pasted the links I found when working. Thanks for adding it, love the collection :)
Will PR next time
